### ISSUE TITLE
SecContentInjection is not yet supported

### ISSUE THREAD

**Issue by dvyas** [andrewnk/docker-alpine-nginx-modsec#1]
I am getting below error when using ContentInjection rule vi /etc/nginx/nginx.conf nginx -s reload 10:26:25 [notice] 118#118: ModSecurity-nginx v1.0.0 10:26:25 [emerg] 118#118: "modsecurity_rules" directive Rules error. File: <>. Line: 1. Column: 16. SecContentInjection is not yet supported. in /etc/nginx/nginx

rg] "modsecurity_rules" directive Rules error. File: <>. Line: 1. Column: 16. SecContentInjection is not yet supported. in /etc/nginx/nginx.conf:66

**Comment by andrewnk** [comment]
This build uses the <a href="https://github.com/SpiderLabs/ModSecurity-nginx">ModSecurity Nginx connector</a> which requires using <a href="https://github.com/SpiderLabs/ModSecurity/tree/v3/master">libModSecurity</a>. SecContentInjection isn't available in libModSecurity: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecContentInjection

**Comment by dvyas** [comment]
Thanks, I am looking to apply CSRF rules , will this image has CSRF rules or you have any idea how I can add CSRF in libmodsecurity . It will be great help

**Comment by andrewnk** [comment]
I haven't found a way to implement something similar to SecContentInjection so I'm going to close this. Please reopen and post a solution if you happen to figure it out.
