### ISSUE TITLE
Updated 3.0.4 modsecurity.conf(-recommended)

### ISSUE THREAD

**Issue by klou** [andrewnk/docker-alpine-nginx-modsec#5]
I just ran into this:

https://github.com/SpiderLabs/ModSecurity/commit/7def498c4c043fd857689c7cc47a64d2bdf0badb#diff-391e1d048530688efb580bb84541320e8a5ff8f8bfb9ebab63a0d30ce2e28f02

Mostly documentation added in that commit, but the changed setting applies to my situation:
```
SecRule MULTIPART_UNMATCHED_BOUNDARY "@eq 1" \
    "id:'200004',phase:2,t:none,log,deny,msg:'Multipart parser detected a possible unmatched boundary.'"
```

**Comment by andrewnk** [comment]
Thanks! I've updated the branches to use the v3.0.4 modsecurity.conf; docker hub images have been updated too.
